api_platform:
    defaults:
        pagination_client_enabled: true
        pagination_items_per_page: 10
        pagination_client_items_per_page: true
    collection:
        pagination:
            items_per_page_parameter_name: itemsPerPage